### ISSUE TITLE
Upload Release Review Approved code changes

### ISSUE THREAD

**Issue by Michael-Angel-Sec** [ansible-lockdown/PGS9-STIG#2]
James/Repo Owners,

Can you provide me access to upload the latest version?  
Description: | RELEASE REVIEW # 124339 for Angel,Michael
Approved for Public Release, 10/07/2019 09:05 AM

Michael Angel
michael.angel@ll.mit.edu

**Comment by jamescassell** [comment]
Thanks! This has been merged.
